#! /bin/sh

# Go up a directory
pushd .
cd ..

# Check out two modules we need (the includes and the web site modules)
cvs -d:pserver:anonymous@cvs1:/cvsroot/libais co libaisutil/include
cvs -d:pserver:anonymous@cvs1:/cvsroot/libais co www

# Return to the directory we were in
popd

# Remove old docs
rm -rf ./htdocs/manual

# Process the files
doxygen ./doxygen.conf

# Remove the source module, we don't need it to sit here
rm -rf ../libaisutil
