#! /bin/sh

# Stuff to doxument (har har har.. *weak cough*)
DOCUMENT=libaisutil
CVSROOT=:pserver:anonymous@cvs1:/cvsroot/libais

# Go 'home'
cd /home/groups/l/li/libais/www

# Check out the website, cgi scripts, and some other stuff
pushd .
cd ..
cvs -d$CVSROOT co www
popd

# Make a temp dir :)
mkdir tmp

# Process each doxygen thingy to generate
for docdir in $DOCUMENT; do
   echo "Doing $docdir.."
   # Check out stuff we need (the includes from this module)
   pushd .
   cd tmp
   cvs -d$CVSROOT co $docdir/include
   popd

   # Process the files
   doxygen ./doxygen/$docdir/doxygen.conf

   # Remove the source module, we don't need it to sit here, and the old web stuff
   echo "Removing source"
   rm -rf tmp/$docdir
done

# Move the new stuff over the old stuff (above)
echo "Moving new stuff over old stuff"
rm -rf ../cgi-bin/* ../htdocs/*
mv cgi-bin/* ../cgi-bin/.
mv htdocs/* ../htdocs/.

# Say we're done, so I don't go insane
echo "Done."
