# $Id$
# Little makefile for developers wishing to bootstrap the package
#

.PHONY: bootstrap

AUTOCONF_DIR=./config
AUTOCONF_FILE=./configure.ac
AUTOCONF_SCRIPT=./configure
AUTOCONF_HEADER=./include/config.h.in

bootstrap:
	libtoolize --copy --force
	aclocal -I $(AUTOCONF_DIR)
	autoheader $(AUTOCONF_FILE) > $(AUTOCONF_HEADER)
	automake --add-missing --copy --include-deps --foreign
	autoconf -I $(AUTOCONF_DIR) -o $(AUTOCONF_SCRIPT) $(AUTOCONF_FILE)
	-chmod 755 $(AUTOCONF_SCRIPT)
